d3b-center/bixtools

- FusionCatcher/latest/Dockerfile
- arriba/latest/Dockerfile
- pizzly/latest/Dockerfile
Added docker files for fusionCatcher, arriba and pizzly.  Dockers for arriba and fusionCatcher mostly unchanged from developers git dockerfile, just created here to have an auto build.  made pizzzly docker since it was missing flatten script on sbg version.
> Mb add fusion catcher

- arriba/1.1.0/Dockerfile
added dockerfile for arriba v1.1.0, so that versioning can be pinned.
> added arriba 1.1.0 docker explicitly

- BIC-seq2/0.7.2/Dockerfile
Using debian base in *critical* for C programs to compile correctly.  Leveraging docker images from https://github.com/ding-lab/BICSEQ2/tree/master/docker were a big help
> :tada: added docker for BIC-seq2

- PureCN/Dockerfile
This allows for easier cl running
> :sparkles: updated purecn docker with optparse package

- gatk/3.8_ubuntu/Dockerfile
gatk 3.8 does not have bgzip and tabix, which is super usefule
> 🔨 added tabix to docker image

- gatk/3.8_ubuntu/Dockerfile
Broad recently moved some of their files to google cloud, including source for gatk 3.8. this should fix the docker file and image.
> 🔧 Fixed source file bug

- annoFuse/0.1.8/annoFusePerSample.R
- annoFuse/0.1.8/dockerfile
- annoFuse/0.1.8/formatFusionCalls.R
Description : 
Updates the docker to download specific release binary files for annoFuse v0.1.8 https://github.com/d3b-center/annoFuse/releases instead of building from master as I did in the existing dockerfile being used
Note:
- Docker image is being tagged with version gaonkark/annofuse:v0.1.8 will need to be updated in cwl
- Also while finding a file to test run I found this run
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-dypmehhf-04/tasks/8bb489d4-d272-437c-aa2c-85c5c7d62682/ where for some reason the parser package (tidyverse) I'm using to read files detects the LeftBreakpoint and RightBreakpoint as date datatype which causes the "NA" to come up in LeftBreakpoint and RightBreakpoint columns in output files if it has very few calls in input files to detect from causing …
> 🐛🔖 adding v0.1.8 annoFuse and bug fix

- star/2.7.5a/Dockerfile
Dockerfile for STAR version 2.7.5a. This version of STAR has updates specifically for single cell RNA.
Part of the single cell RNA ticket for SMART-Seq2: https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/690
> :whale: create dockerfile for STAR 2.7.5a

- .circleci/config.yml
Hello from CircleCI!
We noticed you're exhausting your concurrency limit on the first of the month by [running every minute](https://crontab.guru/#*_*_1_*_*).
Hope this helps!
> Change CircleCI config to run monthly not every minute on the 1st

- .circleci/config.yml
- .circleci/make_config.py
Dockerhub makes the repo names lowercase. In order to push to them, the image paths needed to be adjusted to lowercase.
> 🐛 image repos to lowercase

- gatk/4.beta.1-3.5/Dockerfile
Closes https://github.com/d3b-center/bixu-tracker/issues/847
Ended up having to install the google-cloud-sdk to get this file as the https file in the ticket had protections and could not be downloaded with curl or wget. 
Test with the new docker: https://cavatica.sbgenomics.com/u/d3b-bixu/kf-germline-harmonization-dev/tasks/62b584be-54ad-4280-aa2b-b55dce5d1b95/
> ☁️ get GenomeAnalysisTK from google cloud

- .circleci/config.yml
- peddy/v0.4.2/Dockerfile
This begins to address https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/91. This PR creates a new docker for peddy v0.4.2 which is the current version of peddy that the currently latest docker points to.
> :whale: create peddy v0.4.2 docker image

- .circleci/config.yml
- .circleci/make_config.py
We've come across a major issue where a non-rebased branch overwrote changes done in a previous PR. For the time being, I'm turning off automatic pushing to stop this from negatively affecting our existing images.
> 🔥 turn off automatic pushing

- .circleci/config.yml
- .circleci/make_config.py
Potentially return the automatic pushing. The jist of this is:
1. Diff statements continue to build but not publish the images they create
2. In a PR we'll be able to see if the build happened correct
3. When we merge into master that will trip the new merge block
4. The merge block will compare its HEAD to the previous commit HEAD~1 then build and publish the diff
Major drawback: if in a PR you made changes to a Dockerfile "A" in one commit then do a second commit changing Dockerfile "B", this merge workflow would only catch the last change and build Dockerfile "B".
Counter to the caveat: If we squash all commits at the end of PRs that will not be a problem.
> ⭕️ publish on merge

- .circleci/config.yml
- .circleci/make_config.py
I noticed merging https://github.com/d3b-center/bixtools/pull/92 did not result in the pushing of the created image so I investigated and found that the diff check on master was returning the old filename, which was no longer part of the circleci config. Swapping the `HEAD` and `HEAD~1` in the diff command will return the appropriate filename.
> 💆‍♂️ swap base branch heads

- svaba/1.1.0/Dockerfile
Svaba cannot process CRAMs unless you build a ref seq cache. This update adds that script and a perl script necessary to run it.
Part of https://github.com/d3b-center/bixu-tracker/issues/1564
Needed for https://github.com/kids-first/kf-germline-workflow/pull/22
* Environment:
* Test files:
> 🐛 svaba add ref cache script

- sequenza/3.0.0/Dockerfile
I guess sometime in between me making the original docker and now optparse no longer automatically installs on R 3.5.1 (they added a 3.6 requirement). To get around that I'm grabbing the previous version of optparse that does not require 3.6 and installing it manually.
Additionally it seems like install2.r needs an explicit variable `--error` otherwise it doesn't complain if something cannot be installed and will exit 0. Obviously we should be setting that to fail.
* Environment:
* Test files:
> 🐛  optparse now installs

- octopus/0.6.3-beta/Dockerfile
add refseq cache builder
Something's wrong with the old version of htslib so I just bought us up to the newest release. Also I'm bringing in the samtools ref cache builder script here to speed up the cache creation (octopus is incredibly slow with it to the point where I was just handing it in).
Previous behavior is this would hang for an extended period of time before completing initialization like here in this aborted run: https://cavatica.sbgenomics.com/u/d3b-bixu/dev-canine-workflow/tasks/87f1f0f0-b3fa-4931-ac07-fde553e312c4/stats/. After an hour and a half it's still initialization with no end in side.
**Test …
> 🐎  update htslib;

- cnvnator/v0.4.1/Dockerfile
Added the seq cache populate script to the image. This is necessary for not making CRAM reading such a slog for CNVnator.
Also updated the styling
This runtime is on par with what we see for BAMs: https://cavatica.sbgenomics.com/u/d3b-bixu/kf-germline-harmonization-dev/tasks/1afe79c9-9ca3-4d6d-827b-e588048336a0/
The slight difference in runtime is likely due to the runtime for the seq cache populate tool which takes ~2 minutes per run.
* Environment:
* Test files:
> 🔧  seq cache pop to cnvnator

- .github/workflows/merge_build_push_diff_dockers.yml
Adds github action to build and push changed dockerfiles to cavatica whenever a push/merge happens on the main/master branch affecting any dockerfiles.
Closes https://github.com/d3b-center/bixu-tracker/issues/1833
* Environment:
* Test files:
> 🎉  add merge build and push workflow

- stranded/1.1.0/Dockerfile
For some reason newer versions of the samtools docker screw with the program's ability to find the RSeQC install. Probably related to the python version, but I don't know how to test that. I decided to just rollback the samtools version so we can move forward with this.
* Environment:
* Test files:
> 🐛  rollback samtools

- README.md
- samtools/1.20-parallel/Dockerfile
Adds a docker for samtools 1.20 with GNU parallel and curl
* Environment:
* Test files:
> ✨  docker for samtools with parallel

- .github/workflows/merge_build_push_diff_dockers.yml
Turn off docker push provenance. According to Cavatica and the action release notes, disabling this should result in images being properly displayed on the registry.
Closes https://d3b.atlassian.net/browse/BIXU-3682
* Environment:
* Test files:
> 🤖  disable docker push provenance

- README.md
- tidyverse/4.4.2-gatk-plotter/Dockerfile
New docker for plotting density charts of annotations in Hard Filtered genotyped VCFs. Important for retrospective analysis of hard filtering. 
* Environment:
* Test files:
> 🎉  add docker for plotting GATK hardfilter

- .github/workflows/merge_build_push_diff_dockers.yml
- .github/workflows/pr_build_diff_dockers.yml
Noticed that the updated GHA was trying to build deleted files.
Changes:
- Removed deleted files from the diff report
- Only checking `**/Dockerfile`  in the diff command
* Environment:
* Test files:
> 🐛  do not try to build deleted dockerfiles
