d3b-center/bixtools

- peddy/latest/Dockerfile
fixed run-time error caused by latest version of cyvcf2 and warning from latest version of numpy
> Mb update peddy docker

- gatk/4.3.0-tabix/Dockerfile
Need tabix to index vcf's since the IndexFileFeature in gatk is more like CreateBugFeature
> :tada: Added gatk 4.0.3 with tabix

- cutadapt/latest/Dockerfile
added tool for cutadapt for RNAseq wf
> Mb add cutadapt

- gatk/4.0.12.0/Dockerfile
Added gatk 4.0.12.0, used for unified joint genotyping pipe
> Mb add gatk version

- arriba/1.0.1/Dockerfile
- picard/2.18.9/Dockerfile
- seurat/latest/Dockerfile
Added a seurat docker and also a v1.0.1 arriba docker, so that versions can stay the same when docker auto build occurs, preventing a break in paths when arriba runs.
> Mb add seurat

- star/fusion-1.5.0/Dockerfile
`AS build-env` causes incorrect autobuild.  that was removed
> removed build-env, update apt-get to apt

- VarDictJava/1.5.8/Dockerfile
- bvcftools/Dockerfile
Added a dockerfile for the latest (v1.5.8) version of vardict java.  Also added a utility docker that has bcftools, vcftools, tabix (comes with bgzip).
> Mb add vardict

- VEP/r93/Dockerfile
update vep docker to have maf capability
> Mb update vep

- VEP/r93/Dockerfile
adding in maf requires tabix installed in path
> added back in tabix

- controlfreec/11.5/Dockerfile
- controlfreec/11.5/get_config.pl
Created controlfreec image with version 11.5 and sambamba and necessary R packages built in
> Mb test controlfreec update

- lancet/1.0.7/Dockerfile
Based on Xiao's docker, pinned to a version so that accidental updates don't happen
> added new lancet docker, pinned to a version

- BIC-seq2/0.7.2/Dockerfile
Changed dir ownership and execution bits for better compatibility with cwltool
> chmod and chown root and add execute bit

- BIC-seq2/0.7.2/Dockerfile
- LinkedSV/latest/Dockerfile
- codex2/3.8/Dockerfile
has bic-seq2 fixes, and dockers for linkedsv and codex2 tools
> Mb add linked sv

- PureCN/Dockerfile
- VarDictJava/fp_filter/Dockerfile
- VarDictJava/fp_filter/bcbio_vardict_filter.py
- VarDictJava/fp_filter/utils.py
> Mb add purecn

- VarDictJava/fp_filter/Dockerfile
- VarDictJava/fp_filter/bcbio_vardict_filter.py
- VarDictJava/fp_filter/utils.py
Added bcbio vardict filter and related scripts
> :tada: added bcbio filter docker for vardict

- bed_tools/bedops_plus_bedtools/Dockerfile
- bed_tools/bedopsv2.4.36_plus_bedtools/Dockerfile
Missed a couple of missing semi colons.  Tested locally, build successful
> Mb add bedtools bedops

- VEP/r93_v2/Dockerfile
vcf2maf version changed from v1.6.16 to v1.6.17
> Updated vcf2maf versions from 16 to 17

- annovar/latest/Dockerfile
Added missing libs to complete samltools/hts build (lib curl, open ssl dev)
> :wrench: rm offending trailing `/` in download path

- bvcftools/Dockerfile
- vcf_utils/Dockerfile
simple patch to add bedtools to 2 utility dockers
> :muscle: add bedtools to util docker images bvcftools, and vcfutils

- mend_qc/Dockerfile
Added UCSC Treehouse mend qc docker, modified to better run on cavatica. https://github.com/UCSC-Treehouse/mend_qc
> Mb add mend qc

- VEP/r98/Dockerfile
added a docker for VEP 98 for possible future annotation updates
> :tada: added VEP r98 docker

- svaba/1.1.0/Dockerfile
> :sparkles: svaba1.1.0 dockerfile

- WGSA/Dockerfile
Added WGSA docker, which can be used for annotation
> 🎉Mb add wgsa

- sambamba/0.7.1/Dockerfile
Added latest (0.71) sambamba docker for use in RNAseq SNV wf
> 🎉 added docker for latest sambamba

- gatk/4.1.7.0R/Dockerfile
Docker for the latest version of GATK with R to allow plotting scripts.
Unblocks GATK CNV pipelien development: https://github.com/d3b-center/bixu-tracker/issues/574
> ✨ new gatk docker version with R

- .circleci/config.yml
- .circleci/make_config.py
- freebayes/v1.3.1/Dockerfile
- freebayes/v1.3.2/Dockerfile
This PR adds Dockerfiles for the two most recent versions of freebayes.
> 🐳 freebayes docker

- .circleci/config.yml
- strelka/v2.9.10/Dockerfile
Adds new Dockerfile for Strelka 2.9.10
> ✨ add strelka docker

- .circleci/config.yml
- zumis/2.9.4/Dockerfile
Created docker for zUMIs 2.9.4.
> As add zumis

- .circleci/config.yml
- fastqc/v0.11.9/Dockerfile
Create docker file for fastqc.
Part of https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/817
> :sparkles: add docker for fastqc

- .circleci/config.yml
- .circleci/make_config.py
This PR is for our move to the SBG docker registry. The docker username and password have already been migrated to the new user. The existing config has been changed to switch add the no-longer default registry and changes the image user from kfdrc to d3b-bixu. The make_config.py script has also been updated.
The dockers that failed to build and migrate are here: https://app.circleci.com/pipelines/github/d3b-center/bixtools/854/workflows/9c385727-dd97-4954-8f65-0560f6e58dbb. They must be fixed or just manually carried over.
Part of https://github.com/d3b-center/bixu-tracker/issues/846
> 🐳 great docker migration

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- VEP/r93.7/Dockerfile
This is part of the D3b vcf2maf effort, allows merged cache to be used and pigz added for better cache untar performance. Also added PR template for future PRs
> 🎉 added standalone VEP93 with MSKCC vcf2maf removed and pigz added

- .circleci/config.yml
- kf_vcf2maf/v1.0.0/Dockerfile
Created a docker to pull our modified vcf2maf repo and build
* Environment:
* Test files:
> 🐳 created kf vcf2maf docker

- .circleci/config.yml
- gatk/4.2.0.0R/Dockerfile
This PR adds the new GATK 4.2.0.0 release.
Fixes: all of our problems in life
> ✨ new GATK version

- .circleci/config.yml
- add-strelka2-fields/1.0.0/Dockerfile
This would represent a Dockerfile and circleci config updates for a script that adds the missing fields to Strelka2 VCFs.
* Environment:
* Test files:
* VCF: https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/files/5ffdf91ce4b0a6d32f329e6b/'
* tumor_name  BS_F0GNWEJJ      
* normal_name BS_F5EX3ZY5
> ✨ Nhj strelka2fields docker

- .circleci/config.yml
- .circleci/make_config.py
Diff is running on master after the merge. That's really unnecessary as it just does the same thing as the merge jobs. Also I noticed the recent add_strelka2_fields circleci had erroneous paths; fixed those. Also it looks like we had a duplicate kf_vcf2maf_v1.0.0 merge job.
* Environment:
* Test files:
> 🙈 dont run diff on master

- add-strelka2-fields/1.0.0/Dockerfile
I had to make changes to the location of the output in the Python script that underlies this Dockerfile. Updated Dockerfile to pull the script from the new commit on GitHub. 
* Environment:
* Test files:
> 🔧 update commit from which script is pulled

- .circleci/config.yml
- hotspots/0.1.0/Dockerfile
Adds a docker for hotspots python script.
Part of https://github.com/d3b-center/bixu-tracker/issues/968
* Environment:
* Test files:
> ✨ docker for hotspots

- .circleci/config.yml
- cnvnator/v0.4.1/Dockerfile
Adds Docker for CNVnator 0.4.1. Pretty much just copied the Dockerfile they provide in their [repo](https://github.com/abyzovlab/CNVnator/blob/master/Dockerfile) but changed how the source code is pulled in. I chose the most recent release but the Makefile proved to be problematic. I noticed they had patched that file after the 0.4.1 release so I pull the most recent commit for that file.
Part of https://github.com/d3b-center/bixu-tracker/issues/788
* Environment:
* Test files:
> ✨ cnvnator init

- hotspots/0.1.0/Dockerfile
Updates the HotSpot dockerfile to pull the new script
Part of https://github.com/d3b-center/bixu-tracker/issues/999
* Environment:
* Test files:
> 🔥 update hotspot docker

- consensus-merge/1.0.0/Dockerfile
This is to update the Dockerfile to point at the new version of the underlying script for merge_consensus.
* Environment:
* Test files:
> 🔧  update dockerfile with updated script location

- consensus-merge/1.0.0/Dockerfile
This is just to change the version of the consensus_merge script. The underlying issue was the consistent naming of the hotspot INFO field. 
I believe this is a ticketless hotfix. 
> 🔧 point at new consensus script version

- .circleci/config.yml
- loompy/2.0.16/Dockerfile
Creates a docker image for the loompy library.
* Environment:
* Test files:
> :sparkles: create docker for loompy library

- .circleci/config.yml
- cellranger/3.1/Dockerfile
- cellranger/5.0/Dockerfile
- cellranger/6.0/Dockerfile
This just adds a minimally changed Dockerfile for the newest version of cellranger. It is related to https://github.com/d3b-center/bixu-tracker/issues/975, with 6 in place of 5, but it is not clear that the existing 10X scRNA workflow works with this updated tool, so this does not close that ticket. 
* Environment:
* Test files:
> 🐳 Nhj cellranger 6

- .circleci/config.yml
- consensus-merge/1.1.0/Dockerfile
I created a Dockerfile for a new version of consensus_merge this time since the former version was run 'for real' and this represents meaningful changes. 
This is related to https://github.com/d3b-center/bixu-tracker/issues/1085 although that is closed. 
> 🐳 Nhj consensus docker

- .circleci/config.yml
- picard/2.18.9/Dockerfile
- picard/2.18.9R/Dockerfile
- picard/2.18.9R/VcfSampleRename.py
Add R to the picard 2.18.9 docker. This is the latest version that we have dockers for and making this change should allow all of the picard tools in the alignment workflow to use the same version of picard. This would also mean that we don't need to maintain two versions of picard dockers; one with R one without.
* Environment:
* Test files:
> :heavy_plus_sign: add R to picard 2.18.9 docker

- .circleci/config.yml
- R/4.1.0_SoupX/Dockerfile
This a Dockerfile for R with the SoupX package for removing contamination for single-cell RNAseq data. 
One question is, I made the version equal to the R version (4.1.0). Is this desirable? R of a certain version with a certain packages is the object, but if we have to increment the docker for any reason its version and the R version will be weirdly out of sync. 
There are warnings in the build that the packages V8 and rstan were not successfullly installed, but they do not appear to be necessary. 
This is a step on the road to https://github.com/d3b-center/bixu-tracker/issues/1111, but there will be a follow-on PR with R and CWL. 
* Environment:
* Test files:
- [] My changes generate no new warnings
> 🐳   dockerfile with R + SoupX and dependencies

- .circleci/config.yml
- scrublet/0.2.3/Dockerfile
Fixes # https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/1038
* Environment:
* Test files:
> :sparkles: add Dockerfile for scrublet

- .circleci/config.yml
- scrublet/0.2.3/Dockerfile
- soupx_R/4.1.0_SoupX/Dockerfile
Partially Fixes # https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/1038
* Environment:
* Test files:
> Add scanpy to scrublet docker and dropletutils to soupx docker

- .circleci/config.yml
- annotsv/3.1.1/Dockerfile
Adds Dockerfile for AnnotSV version 3.1.1
Part of https://github.com/d3b-center/bixu-tracker/issues/1192
* Environment:
* Test files:
> 🎉  added annotsv dockerfile

- .circleci/config.yml
- pyspark/3.1.2/Dockerfile
This docker was created in support of creating a vcf-to-parquet file conversion tool by installing pyspark and glow.
Fixes # https://github.com/d3b-center/bixu-tracker/issues/1268
* Environment:
* Test files:
> 🎉 Created pyspark docker

- .circleci/config.yml
- toolkit_subtyping/pyreader0.4.4/Dockerfile
Adds python libraries to toolkit docker.
* Environment:
* Test files:
> :sparkles: add python modules to toolkit docker

- .circleci/config.yml
- ngscheckmate/1.3/Dockerfile
Ported and updated dockerfile for running NGS Checkmate. This is needed imminently for the openPBTA publication
* Environment:
* Test files:
> :tada: added ngscheckmate

- ngscheckmate/1.3/Dockerfile
I got too cute in building off the existing samtools docker and cut too many packages. This restores that.
* Environment:
* Test files:
> 🔧 fixed missing packages for vcftool and bcftools install

- .circleci/config.yml
- .circleci/make_config.py
- sentieon/202112.01_hifi/Dockerfile
Sentieon docker with samtools added.
* Environment:
* Test files:
> 🎉  sentieon 202112.01_hifi added

- .circleci/config.yml
- samtools/1.15.1/Dockerfile
Add new samtools docker.
* Environment:
* Test files:
> 🎉  add samtools 1.15.1

- .circleci/config.yml
- cutesv/1.0.13/Dockerfile
Add cutesv docker
* Environment:
* Test files:
> 🎉  cutesv 1.0.13 added

- .circleci/config.yml
- sniffles/2.0.3/Dockerfile
Add sniffles docker.
* Environment:
* Test files:
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202124553793013
> 🎉  add sniffles docker

- .circleci/config.yml
- pypy/3.9-7.3.9-bullseye/Dockerfile
- pypy/Dockerfile
This PR introduces PyPy image to bixtools. PyPy can improve the performance of python code. This image will have preinstalled NumPy, pandas, SciPy and PyReadr module. It will take between 30-60 mins to build based on the number of cores available. 
* Environment: Ubuntu
* Test files: None
> Add PyPy image

- .circleci/config.yml
- pypy/3/Dockerfile
This PR changes PyPy base image that was merged previously. We encountered an error while running the code with this image. 
Change the base image to PyPy:3
* Environment: ubuntu and PyPy:3 base image
* Test files: None
> Change PyPy image

- .circleci/config.yml
- annoFuse/0.91.0/Dockerfile
- annoFuse/0.91.0/annoFusePerSample.R
- annoFuse/0.91.0/formatFusionCalls.R
This PR brings in a docker for latest version of annofuse.
This was test locally by building the docker image and running annofuse within the container. It takes close to 15 mins to build this images
> Feature/annofuse:v0.91.0

- .circleci/config.yml
- toolkit_subtyping/subtyping_v1.0/Dockerfile
This PR:
- adds pytest to subtyping docker
- tags versions of some R packages used
Partially Fixes # https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/gh/d3b-center/bixu-tracker/1621
* Environment:
* Test files:
> :whale: add pytest to toolkit docker

- star/fusion-1.10.1/Dockerfile
An ancient branch that tidies up how this docker is built to use the Cavatica STAR image as its start point instead of my personal git repo
* Environment:
* Test files:
> 🔨 small update to build from cavatica registry version

- .circleci/config.yml
- FusionAnnotator/0.1.1/Dockerfile
Ported over Dockerfile used to generate a prod docker image from https://github.com/kgaonkar6/tools/blob/master/FusionAnnotator/Dockerfile (thanks @sickler-alex !). Updated ubuntu image and also added pigz to speed up untar of large reference tar ball.
Fixes # https://github.com/d3b-center/bixu-tracker/issues/1748
* Environment:
* Test files:
> 🎉 ported over fusionannnotator

- .circleci/config.yml
- LOH/1.0.0/Dockerfile
Adds bam readcount tool to loh docker
* Environment:
* Test files:
> Add bam readcount to loh docker

- .circleci/config.yml
- annoFuse/0.92.0/Dockerfile
This docker incorporates bug fixes and reference file updates implemented in https://github.com/d3b-center/annoFuse/releases/tag/v0.92.0 and https://github.com/d3b-center/annoFuseData/releases/tag/v0.1.0. I also removed the addition of custom R scripts for the following reasons:
1. I now better understand that annoFuse is more like a library that you import to do things, not a standalone command line tool; therefore, it pretty much always has to be wrapped dpending on what you're doing with it
2. Script import into cwl is the way to go, and these scripts will be moved to the workflow
3. I have the opportunity to use the fusion_standardization function built into annoFuse instead of the custom one, which will narrow the gap of cross-platform compatibility by reducing variability in file …
> 🎉 annoFuse 0.92.0

- .circleci/config.yml
- lancet/1.1.x/Dockerfile
TGEN Coyote uses the 1.1.x version of Lancet for their pipeline. Here I make the Dockerfile for that. I don't like that we have to make it based off the release so here I hardcode the specific commit that is the most recent one.
* Environment:
* Test files:
> 🎉  lancet 1.1.x docker for canine

- .circleci/config.yml
- octopus/0.6.3-beta/Dockerfile
🔴  update circleci config
🐙 🐳 🐺 
* Environment:
* Test files:
> 🐙  octopus docker for canine

- .circleci/config.yml
- msisensor/1.1.a/Dockerfile
MSIsensor docker for canine. Took the basic frame from [here](https://github.com/tgen/jetstream_containers/blob/main/tgen_tempe/Individual_Images/m/msisensor/1.1a/Dockerfile) and made it actually work for the general public.
* Environment:
* Test files:
> 🎉  msisensor docker for canine

- .circleci/config.yml
- snpEff/4.3t/Dockerfile
🔴  update circleci
snpEff docker for canine. Looks like we had an old dockerfile in that directory that's the same version but didn't fit my needs.
* Environment:
* Test files:
> 🎉  add snpeff docker for canine

- .circleci/config.yml
- VarDictJava/1.7.0/Dockerfile
New version of VardictJava for the canine workflow
* Environment:
* Test files:
> 🎉  new vardict for canine

- .circleci/config.yml
- sequenza/3.0.0/Dockerfile
Sequenza docker for canine.
* Environment:
* Test files:
> 🎉  sequenza 3.0.0 init

- .circleci/config.yml
- python/3.9-canine-util/Dockerfile
🔴  update circleci config
🐍 🐳 🐺 
* Environment:
* Test files:
> 🎉  python util docker for canine

- .circleci/config.yml
- tidyverse/3.6.1-canine-util/Dockerfile
🔴  update circleci config
🏴‍☠️ 🐳 🐺 
* Environment:
* Test files:
> 🎉  catchall tidyverse docker for canine

- octopus/0.6.3-beta/Dockerfile
Noticed some failures when I plugged the newly cavatica docker into my canine workflow. Made some adjustments here as well as cleaned up the code.
* Environment:
* Test files:
> 🐛  octopus docker fix and cleanup

- .circleci/config.yml
- hisat2/2.2.1/Dockerfile
I had a strong desire to build a GENCODE 39 reference to match our bulk RNAseq. The Human Cell Atlas docker was older and unable to to do so, but building the latest release was successful
Fixes # https://github.com/d3b-center/bixu-tracker/issues/1697
* Environment:
* Test files:
> 🎉 Created hisat2 docker

- .circleci/config.yml
- LOH/1.0.1/Dockerfile
Adding samtools to previous loh 1.0.0 docker image. Review the dockerfile from line number 31
* Environment:
* Test files:
>  Add samtools to loh

- .circleci/config.yml
- toolkit_immune_deconvolution/1.0.0/Dockerfile
This PR brings immune deconvolution docker.
* Environment:
* Test files:
> Immune deconvolution docker

- .github/workflows/update_readme_dockers.yml
- README.md
Trying something to make sure our README is always up to date with the Dockers in the repo
* Environment:
* Test files:
> 🤖  readme builder gha

- .github/workflows/monthly_pull_check_dockers.yml
- README.md
New to this PR:
- Adds a new action that we weren't doing in circleci. All it does is pull all expected dockers from Cavatica. Useful for users to see what is actually on Cavatica and able to be pulled.
- This triggers monthly but users can run it on their own.
- Added a badge to README for users and tracking status
* Environment:
* Test files:
> 🎉  gha monthly docker pull check

- .github/workflows/monthly_build_check_dockers.yml
- README.md
This PR adds a monthly build check for all dockers in the repository; users can also trigger this workflow on their own.
Also adds a badge to the README so that everyone can see which dockers are failing to build at all times 😬 
* Environment:
* Test files:
> 🎉  gha monthly docker build check

- .github/workflows/pr_build_diff_dockers.yml
- README.md
Adds github action to build Dockerfiles that are being changed by a PR.
* Environment:
* Test files:
> 🎉  new PR docker builder

- .github/workflows/monthly_build_check_dockers.yml
- .github/workflows/monthly_pull_check_dockers.yml
Fixing the monthly builds. Had some bad labels.
Closes https://github.com/d3b-center/bixu-tracker/issues/1885
* Environment:
* Test files:
> 🤖 🐛  fix monthlys

- sniffles/2.0.3/Dockerfile
Fixing this older sniffles docker that was missing a library. Also sneaky testing the new gha workflows.
* Environment:
* Test files:
> 🐛  sniffles now builds

- README.md
- cutesv/2.0.3/Dockerfile
New Docker for cuteSV 2.0.3
Part of https://github.com/d3b-center/bixu-tracker/issues/1848
* Environment:
* Test files:
> 🎉  new cuteSV docker

- README.md
Reverts d3b-center/bixtools#182
> Revert "Update README Docker Table"

- tumor-only-benchmarking/1.0.0/Dockerfile
Configuring RTG tool within the docker by just running it once inside the docker.
* Environment:
* Test files:
> config rtg within the docker

- README.md
- cellranger/6.1.2/Dockerfile
Unfortunately, will be doomed to fail over time as it requires token, but will likely stay alive long enough for this PR.
Has bug fixes that makes CR v6 work better
* Environment:
* Test files:
> 🚀 Add cell ranger v6.1.2

- README.md
- tumor-only-benchmarking/1.0.0/Dockerfile
Add htslib to this docker
* Environment:
* Test files:
> Add htslib

- echtvar/0.1.9/Dockerfile
Part of https://github.com/d3b-center/bixu-tracker/issues/2108
* Environment:
* Test files:
> 🎉  add echtvar 0.1.9

- tumor-only-benchmarking/1.0.0/Dockerfile
Add matplotlib to improve filter analysis side of tumor only benchmarking
* Environment:
* Test files:
> Add matplotlib

- .github/workflows/update_readme_dockers.yml
Adding [permissions scope](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) for github actions to allow pull request creation
> Add permissions for github actions

- README.md
- cellranger/6.1.2/Dockerfile
- scRNA_qc/v1.0.0/Dockerfile
Used to run custom QC R makrdown notebook as part of 10X workflow
* Environment:
* Test files:
> ✨ Added QC Docker Image

- README.md
- scRNA_qc/v1.0.0/Dockerfile
- scRNA_qc/v1.0.1/Dockerfile
Pulled from Tidyverse and came to an agreement with Tonia as to what version of Seurat to use. Shaved off ~700MB in size.
Fixes # https://github.com/d3b-center/bixu-tracker/issues/2186
* Environment:
* Test files:
> 🦾 Streamline scRNA Qc Docker

- README.md
- scdblfinder/v1.12.0/Dockerfile
Continuing the work of improving the Single Cell docker images. Build time is not much faster, but nearly 2GB smaller
Fixes # https://github.com/d3b-center/bixu-tracker/issues/2186
* Environment:
* Test files:
> ⬆️ Upgraded scDblFinder Image

- README.md
- soupx_R/1.6.2/Dockerfile
- star/2.7.10b/Dockerfile
- star/2.7.11a/Dockerfile
For STAR Solo, I have two versions of STAR, one that matches that latest Sentieon has, the other is simply the latest that I might need for STAR Diploid in the future. For SoupX, to match the version of R being used, I have updated the image and built off of the QC image for ease of build.
Fixes # https://github.com/d3b-center/bixu-tracker/issues/2150
* Environment:
* Test files:
> 🚀 New STAR and SoupX Docker

- README.md
- scRNA_qc/v1.1.0/Dockerfile
Tonia has updated the scRNA QC script to incorporate miQC, a more automated way to do initisl filter and QC of single cell data 
Fixes # https://github.com/d3b-center/bixu-tracker/issues/2149
* Environment:
* Test files:
> ✨ create new QC docker

- README.md
- supremo/0.1.0/Dockerfile
- supremo/1.0.0/Dockerfile
New Docker for supremo
* Environment:
* Test files:
> 🐳  supremo docker

- README.md
- stranded/1.1.0/Dockerfile
New version of stranded that includes the following changes: https://github.com/zoomzoom1011/how_are_we_stranded_here/pull/1
Part of https://github.com/d3b-center/bixu-tracker/issues/1871
* Environment:
* Test files:
> 🐳  new stranded version

- README.md
- echtvar/0.2.0/Dockerfile
Author has made the 0.2.0 release on git with pre-built binary, which makes for a much smaller image
Fixes # https://github.com/d3b-center/bixu-tracker/issues/2258
* Environment:
* Test files:
> ✨Echtvar 0.2.0 Release

- README.md
- plink/1.90b7.2/Dockerfile
Adds plink 1.90 docker
Part of https://github.com/d3b-center/bixu-tracker/issues/2297
* Environment:
* Test files:
> ✨  add plink 1.90b7.2

- README.md
- t1k/v1.0.5/Dockerfile
Dockerize t1k version 1.0.5
Part of https://github.com/d3b-center/bixu-tracker/issues/2332
* Environment:
* Test files:
> 🎉  added t1k 1.0.5 docker

- README.md
- minimap2/v2.28/Dockerfile
- nanocount/v1.1.0/Dockerfile
> 🦄 adding minimap2 and nanocount for ONT wf

- README.md
- bcftools/1.20/Dockerfile
While other institutions have valid bcftools images, the institution we've been pulling from did not properly build/reference plugins, so it doesn't work. This image will have working plugins and a complete htslib build
* Environment:
* Test files:
> 🎉 BCFTOOLS 1.20

- README.md
- pbfusion/v0.4.1/Dockerfile
> ⭐ pbfusion

- cutadapt/3.4/Dockerfile
> 🔧 updating image functionality (including samtools and bc)

- t1k/v1.0.5/Dockerfile
Update latest T1k Docker with software necessary to process CRAM files
Part of: https://d3b.atlassian.net/browse/BIXU-2332
* Environment:
* Test files:
> 🔧  T1k CRAM support

- annoFuse/0.92.0/Dockerfile
Fixes an issue in which some fusions were listed twice with split annotations. This was due to a bug in that annotation data source. That file was fixed by https://github.com/d3b-center/annoFuseData/pull/12 and repo properly updated for versioning by https://github.com/d3b-center/annoFuseData/pull/13 
Fixes # https://d3b.atlassian.net/browse/BIXU-2325
Fusion `NSD3--TRIP12` no longer duplicated in output
* Environment:
* Test files:
> 🔧 Update annoFuse

- hbc_scrna_qc/scrnaseq/Dockerfile
To accommodate a minor refactor in the scRNA QC output, adding this package. It will allow for writing of QC-filtered 10X count matrices in h5 format
Fixes # https://d3b.atlassian.net/browse/BIXU-1048
* Environment:
* Test files:
> 🔨  add droplet utils

- README.md
- toolkit_python/3.0.0/Dockerfile
This PR adds a docker for the python modules I need for TMB input validation.
Fixes # https://d3b.atlassian.net/browse/BIXU-3821
* Environment:
* Test files:
> :whale: create docker for toolkit python libraries

- toolkit_immune_deconvolution/1.1.0/Dockerfile
Adds a new docker for immune deconvolution.
Partially Fixes # https://d3b.atlassian.net/browse/BIXU-3843
* Environment:
* Test files:
> :whale: update docker for immune deconvolution

- README.md
- toolkit_immune_deconvolution/1.1.0/Dockerfile
Fixes a bug in my last PR. The immunedeconv library was silently failing and not actually getting installed. I also forgot to merge the auto PR that updates the docker table.
* Environment:
* Test files:
> :whale: fix silent error when installing immunedeconv library

- README.md
- toolkit_splicing_data_products/1.0.0/Dockerfile
This PR creates an R docker for use in the splicing modules within the toolkit project.
* Environment:
* Test files:
> :whale: add docker for R libraries used in splicing

- .github/workflows/merge_build_push_diff_dockers.yml
- .github/workflows/pr_build_diff_dockers.yml
Addresses the dependabot vulnerability.
* Environment:
* Test files:
> 🤖  update changed-files GHA

- README.md
- cbio-etl/v1.0.0/Dockerfile
- cbio-etl/v2.2.0/Dockerfile
Created a Dockerfile for cbio-etl tool
* Environment:
* Test files:
> 🎉 add cbio-etl tool
